### ISSUE TITLE
Extract EidNym generators and Curve

### ISSUE THREAD

**Issue by adecaro** [IBM/idemix#53]
At present, there is no method to extract the generators used in computing `EidNym` from the issuer's public key. These generators could potentially be utilized in creating other ZK proofs involving EidNym.

This GitHub issue proposes implementing a mechanism to extract these generators. One potential solution would be to receive the generators during the key import process. This could be achieved by augmenting the IdemixIssuerPublicKeyImportOpts struct with an additional field that carries the generators.

Same reasoning is for the elliptic curve used.

**Comment by ale-linux** [comment]
I thought about it and retrieving the generators there might be a bit tricky - you don't necessarily know which generator is used for which attribute, because we're trying to hide this from the user. How about instead we return the generators in the places where we create the commitments?

**Comment by adecaro** [comment]
The bases of EidNym are part of the ZK statement, we need to know before generating any commitment with those bases. This is the issue, unfortunately.

**Comment by ale-linux** [comment]
right but the commitment will be generated independent of any statement, because the API that generate it are unaware of anything else. Why can't you pre-generate the nyms?

**Comment by ale-linux** [comment]
Nope. As we generate commitments with the API, we get back the bases that were used. Then we can use base, commitment and witnesses to generate proof for any additional statements we might need

**Comment by adecaro** [comment]
A proposal to address this issue is the following: We can introduce a new opt to import an elliptic curve-based issuer public key. This new opt will be used by code that must enforce that the issuer public key uses a given crypto technology. 
This opt will allow the developer to get access to the bases used to compute the various commitments. 
These bases can be organised in a map. A key takes value from an enum naming the available commitments (EID, RH, Secret). A value is an array of elements.
